# Site settings
title: Hi, I'm Rachel
email: rwhlee0@gmail.com
url: https://rachleee.github.io
description: "I'm currently a computer science student in Trent University. I'm interested in Data Analyst, Data Science, Bioinformatics, and Biotech."
keywords: "your keywords, separated by commas"
skills: "Data Analyst - Data Science - Research - UX/UI Design"
meta_author: Lee Rachel

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Rachel Lee
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/rachel-lee-3789621b1/
  - title: facebook
  - title: github
    url: http://github.com/rachleee

# Postal address (add as many lines as necessary)
address:
  - line: GTA (Greater Toronto Area)

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
